### ISSUE TITLE
How to read from stdin and write to stdout?

### ISSUE THREAD

**Issue by guest271314** [mozilla-spidermonkey/sm-wasi-demo#3]
I'm trying to figure out how to implement jsshell (JavaScript-C117.0a1) as a Native Messaging host. I'm not sure how to read from stdin using `readline()` and `readlineBuf()` to read stdin until completion, e.g., 1 MB of input. I think I should be able to use `print()` to pass length of message in native byte order to stdout, though I havn't gotten that far; I'm still trying to read stdin.

**Comment by jandem** [comment]
Are you able to read anything with `readline` or does it always return `null`?

Does it have to be stdin/stdout? You could also consider using a file on the in-memory file system, this works for me with the online demo:
```js
let s = "hello";
let tarr = new Uint8Array(s.split("").map(s => s.charCodeAt(0)));
os.file.writeTypedArrayToFile("/foo", tarr);
print(os.file.readFile("/foo")); // hello
```
The online demo uses this to pass the source code to the Wasm environment (`/input.js`).

**Comment by guest271314** [comment]
The tests so far return `null`. I tried to write to the result of `readline()` to local local filesysten and nothingwas printed or encoding error. I wasn't able to write to stdout with `putstr()` or `print()`, either. I suppose my next attempt will be embedding JavaScript text and using process substitution in a Bash script https://github.com/guest271314/native-messaging-webassembly/blob/main/nm_c_wat.sh. It looks like `readline()` and `print()` are only expecting a TTY? 

Sure would help if we had dedicated I/O methods that did not expect only TTY.

**Comment by guest271314** [comment]
It looks like this https://hg.mozilla.org/mozilla-central/file/tip/js/src/shell/js.cpp#l62
 is available only in WASI

```
#ifndef __wasi__
static bool ReadAll(int fd, wasm::Bytes* bytes) {
  size_t lastLength = bytes->length();
  while (true) {
    static const int ChunkSize = 64 * 1024;
    if (!bytes->growBy(ChunkSize)) {
      return false;
    }

    intptr_t readCount;
    while (true) {
      readCount = read(fd, bytes->begin() + lastLength, ChunkSize);
      if (readCount >= 0) {
        break;
      }
      if (errno != EINTR) {
        return false;
      }
    }

    if (readCount < ChunkSize) {
      bytes->shrinkTo(lastLength + readCount);
      if (readCount == 0) {
        return true;
      }
    }

    lastLength = bytes->length();
  }
}

static bool WriteAll(int fd, const uint8_t* bytes, size_t length) {
  while (length > 0) {
    int written = write(fd, bytes, length);
    if (written < 0) {
      if (errno == EINTR) {
        continue;
      }
      return false;
    }
    MOZ_ASSERT(unsigned(written) <= length);
    length -= written;
    bytes += written;
  }

  return true;
}

class AutoPipe {
  int fds_[2];

 public:
  AutoPipe() {
    fds_[0] = -1;
    fds_[1] = -1;
  }

  ~AutoPipe() {
    if (fds_[0] != -1) {
      close(fds_[0]);
    }
    if (fds_[1] != -1) {
      close(fds_[1]);
    }
  }

  bool init() {
#  ifdef XP_WIN
    return !_pipe(fds_, 4096, O_BINARY);
#  else
    return !pipe(fds_);
#  endif
  }

  int reader() const {
    MOZ_ASSERT(fds_[0] != -1);
    return fds_[0];
  }

  int writer() const {
    MOZ_ASSERT(fds_[1] != -1);
    return fds_[1];
  }

  void closeReader() {
    MOZ_ASSERT(fds_[0] != -1);
    close(fds_[0]);
    fds_[0] = -1;
  }

  void closeWriter() {
    MOZ_ASSERT(fds_[1] != -1);
    close(fds_[1]);
    fds_[1] = -1;
  }
};
#endif  // __wasi__

int shell::sArgc;
char** shell::sArgv;

#ifndef __wasi__
```

not in a shell script using `./js`. 

Looks similar to this code I use for Deno and Node.js hosts

```
#!/usr/bin/env -S ./deno run --v8-flags="--expose-gc,--jitless"
 // Deno Native Messaging host
// guest271314, 10-5-2022

// https://github.com/denoland/deno/discussions/17236#discussioncomment-4566134
// https://github.com/saghul/txiki.js/blob/master/src/js/core/tjs/eval-stdin.js
async function readFullAsync(length) {
  const buffer = new Uint8Array(65536);
  const data = [];
  let n = null;
  while (data.length < length && (n = await Deno.stdin.read(buffer))) {
    data.push(...buffer.subarray(0, n));
  }
  return new Uint8Array(data);
}

async function getMessage() {
  const header = new Uint32Array(1);
  await Deno.stdin.read(new Uint8Array(header.buffer));
  return readFullAsync(header[0]);
}
```

Here's what I have so far based on a QuickJS Native Messaging host that does not work as expected 

```
#!/usr/bin/env -S ./js --enable-top-level-await
// SpiderMonkey Native Messaging host

function getMessage() {
  const stdin = readline();
  const data = new Uint8Array([...stdin].map((char) => char.charCodeAt(0)));
  //const length = data.subarray(0, 4);
  //const input = data.subarray(4);
  //os.file.writeTypedArrayToFile('length.txt', length);
  os.file.writeTypedArrayToFile('getMessage.txt', data);
  return data.subarray(4);
}

function sendMessage(message) {
  os.file.writeTypedArrayToFile('sendMessage.txt', message);
  const header = Uint32Array.from(
    {
      length: 4,
    },
    (_, index) => (message.length >> (index * 8)) & 0xff
  );
  const output = new Uint8Array(header.length + message.length);
  output.set(header, 0);
  output.set(message, 4);
  print(header);
  print(message);
}

function main() {
  while (true) {
    const message = getMessage();
    sendMessage(message);   
    break;
  }
}

try {
  main();
} catch (e) {

}
```

It doesn't look like it's possible to read and write `TypedArray`s from stdin and stdout, respectively using `./js` alone?

**Comment by jandem** [comment]
> It looks like this https://hg.mozilla.org/mozilla-central/file/tip/js/src/shell/js.cpp#l62
> is available only in WASI

The `#ifndef __wasi__` around `ReadAll` means it's *not* available in WASI. It's because we currently only use this for some Wasm cross-process serialization testing functions.

I'm not sure off-hand why `readline` is always returning `null`. I suspect it's possible to make this work in the WASI host environment somehow but I'm not sure.

**Comment by guest271314** [comment]
I'm not running jsshell in a WASI environment. I'm running jsshell standalone trying to implement a Native Messaging host https://github.com/guest271314/NativeMessagingHosts using SpiderMonkey. The I/O is not working as expected.

**Comment by jandem** [comment]
In that case let's close this issue and continue in [the Discourse thread](https://discourse.mozilla.org/t/why-is-this-spidermonkey-native-messsaging-host-not-sending-stdout-to-the-client/120924/3).
